language: python
python:
  - "3.6"

install: "pip install -r requirements.txt"

env:
    global:
        - PYTHONPATH=src

    matrix:
        - TASK=test
        - TASK=coverage


script:
    - make $TASK
