language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"

env:
  - PYTHONPATH=src
# command to run tests
script:
  - python -m pytest tests --durations=10
  - python -m coverage run --branch --include='src/*.py' -m pytest tests/ --hypothesis-profile=coverage
  - python -m coverage report --fail-under=100 --show-missing
